web/router.ex
defmodule Mongue.Router do
  use Mongue.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Mongue do
    pipe_through :browser # Use the default browser stack

    post "/search", SearchController, :search
    get "/search", SearchController, :index

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Mongue do
  #   pipe_through :api
  # end
end

lib/mongue/endpoint.ex
defmodule Mongue.Endpoint do
  use Phoenix.Endpoint, otp_app: :mongue

  socket "/socket", Mongue.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :mongue, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_mongue_key",
    signing_salt: "bgSRYPVV"

  plug Mongue.Router
end

lib/mongue/repo.ex
defmodule Mongue.Repo do
  use Ecto.Repo, otp_app: :mongue
end

web/models/book.ex
defmodule Mongue.Book do
  use Mongue.Web, :model
  @derive [Poison.Encoder]
  
  schema "books" do
    field :title, :string
    field :link, :string
    field :cover_s_url, :string
    field :cover_l_url, :string
    field :description, :string
    field :author, :string
    field :pub_nm, :string
    field :category, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :link, :cover_s_url, :cover_l_url, :description, :author, :pub_nm, :category])
    # |> validate_required([:title, :link, :cover_s_url, :cover_l_url, :description, :author, :pub_nm, :category])
  end
end

web/controllers/page_controller.ex
defmodule Mongue.PageController do
  use Mongue.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/search_controller.ex
defmodule Mongue.SearchController do
  use Mongue.Web, :controller

  def index(conn, _params) do
    render conn, "index.html", items: %{}
  end

  def search_bar(conn, params) do
    IO.puts "haha"
    render conn, "search_bar.html", items: %{}
  end

  def search(conn, params) do
    api_key = "d692fc1d9a302e26c4ea268cab4e2e37"
    url = "https://apis.daum.net/search/book?"
    output_type = "json"
    cate_id = "47"
    search_type = "title"
    sort = "popular"
    # params["search"]["keyword"] = String.replace params["search"]["keyword"], " ", "+"
    IO.puts params[:search][:keyword]
    full_url = "#{url}apikey=#{api_key}&q=\"#{URI.encode params["search"]["keyword"]}\"&output=#{output_type}"
              <> "&cate_id=#{cate_id}&search_type=#{search_type}&sort=#{sort}"

    case HTTPoison.get!(full_url) do

      %HTTPoison.Response{status_code: 200, body: body} ->
        %{"channel" => %{"item" => items}} = Poison.decode!(body)
        render conn, "index.html", items: items

      %HTTPoison.Response{status_code: 404} ->
        IO.puts "Not found :("
      %HTTPoison.Error{reason: reason} ->
        IO.insepct reason
      _ -> IO.puts "what"
    end

  end
end

web/views/error_view.ex
defmodule Mongue.ErrorView do
  use Mongue.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/index_view.ex
defmodule Mongue.SearchView do
  use Mongue.Web, :view

  def is_item_nil?("" = item), do: true
  def is_item_nil?(item), do: false
  def replace_tag(str) do
    str
    |>  String.replace("<b>", "<font style='color:orange'%>")
    |>  String.replace("</b>", "</font>")

  end
end

web/views/layout_view.ex
defmodule Mongue.LayoutView do
  use Mongue.Web, :view
end

web/views/page_view.ex
defmodule Mongue.PageView do
  use Mongue.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Mongue!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>
    <div class="left-panel">
      <div class="left-header">
        <div class="name">
        MONGUE DB
        </div>
        <div class="version">
          V. 0.1
        </div>

      </div>
      <div class="left-search">

        <%= render Mongue.SearchView, "search_bar.html", assigns %>
      </div>

    </div>

    <div class="right-panel">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="front-item front-item-1">
  <h2> <span>Search the book you want<span class="spacer"></span></span></h2>
</div>
<div class="front-item front-item-2">
<h2> <span>Read that goddamn book you picked<span class="spacer"></span></span></h2>
</div>
<div class="front-item front-item-3">
<h2> <span>Pay that motherfucking money<span class="spacer"></span></span></h2>
</div>

web/templates/search/index.html.eex
  <%= case @items do %>

  <% [] ->  %>
   Nothing to display
  <% _ -> %>
    <%= for item <- @items do %>
    <%= render "item.html", item: item %>
    <% end %>
  <% end%>

web/templates/search/item.html.eex
<div class="row" style="padding:10px;">
  <div class="col-sm-3">
    <%= if is_item_nil?(@item["cover_l_url"]) do %>
      <div> Page cover is not available </div>
    <%= else %>
    <%= raw("<image src=#{HtmlEntities.decode @item["cover_l_url"]}/>") %>
    <% end %>
  </div>
  <div class="col-sm-8 row">
    <div class="col">
    Title: <%=
      @item["title"]
      |> replace_tag
      |> HtmlEntities.decode
      |> raw
      %>
    </div>
    <div class="col">
    Description: <%=  HtmlEntities.decode @item["description"] %>
    </div>
    <div class="col">
    Publisher: <%= HtmlEntities.decode @item["pub_nm"] %>
    </div>
    <div class="col">
      Detail: <%= link "View", to: @item["link"] %>
    </div>
  </div>
  <div class="col-sm-1">
    Location: I'm here
  </div>
</div>

web/templates/search/search_bar.html.eex
<%= form_for @conn, search_path(@conn, :search), [as: :search], fn f -> %>
<div>

</div>
<div class="row">
  <div class="col-sm-1">
  </div>
  <div class="col-sm-10 float-left">
    <span class="left-search-glyph float-left glyphicon glyphicon-search" aria-hidden="true"></span>   <%= text_input f, :keyword, placeholder: "Title" %>
  </div>
  <div class="col-sm-1">
    <%= submit "SEARCH", class: "hidden" %>
  </div>
  <div class="left-menu">
  </div>
</div>
<% end %>